# Guided Project: Exploring Ebay Car Sales Data

The aim of this project is to clean and analyze the included used car listings.

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# read in data
autos = pd.read_csv('autos.csv', encoding='Latin-1')

In [3]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [4]:
# some stats about Autos
autos.info()
autos.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

### Observations
- missing values in `vehicletype`, `gearbox`,`model`,`fuelType`,`notRepairedDamage`
- some incorrect datatypes (dates are objects, rather than datetimes)
- price includes dollar sign and is object
- odometer includes km and is object
- model names are very specific (include options); likely will need to be simplified to do any comparison of models

## Cleaning column names

In [5]:
# view column names
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [6]:
# rename columns
cols = {'yearOfRegistration':'registration_year',
            'monthOfRegistration':'registration_month',
            'notRepairedDamage':'unrepaired_damage',
            'dateCreated':'ad_created',
            'offerType':'offer_type',
            'vehicleType':'vehicle_type',
            'fuelType':'fuel_type',
            'nrOfPictures':'no_of_pictures',
            'postalCode':'postal_code',
            'lastSeen':'last_seen',
            'dateCrawled':'date_crawled'}
autos.rename(columns=cols, inplace=True)

In [7]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,no_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

- changed columns from camelCase to snake_case for consistency and to make writing additional easier

## Initial Exploration and Cleaning

In [8]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,no_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-19 17:36:18,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [9]:
autos['seller'].value_counts()

privat        49999
gewerblich        1
Name: seller, dtype: int64

In [10]:
autos['offer_type'].value_counts()

Angebot    49999
Gesuch         1
Name: offer_type, dtype: int64

In [11]:
autos['abtest'].value_counts()

test       25756
control    24244
Name: abtest, dtype: int64

In [12]:
autos['gearbox'].value_counts()

manuell      36993
automatik    10327
Name: gearbox, dtype: int64

In [13]:
autos['unrepaired_damage'].value_counts()

nein    35232
ja       4939
Name: unrepaired_damage, dtype: int64

In [14]:
autos['name'].value_counts()

Ford_Fiesta                                                         78
Volkswagen_Golf_1.4                                                 75
BMW_316i                                                            75
BMW_318i                                                            72
Volkswagen_Polo                                                     72
Opel_Corsa                                                          71
BMW_320i                                                            71
Renault_Twingo                                                      70
Volkswagen_Golf                                                     57
Opel_Corsa_1.2_16V                                                  56
BMW_116i                                                            53
Peugeot_206                                                         52
Opel_Corsa_B                                                        52
Ford_Focus                                                          50
Volkswagen_Polo_1.2                                                 48
Volkswagen_Golf_1.6                                                 47
Opel_Astra                                                          43
Opel_Corsa_1.0_12V                                                  41
Volkswagen_Passat_Variant_1.9_TDI                                   39
BMW_320d_DPF_Touring                                                38
BMW_520i                                                            37
Opel_Astra_1.6                                                      35
Audi_A4_Avant_2.0_TDI_DPF                                           34
Renault_Twingo_1.2                                                  33
Ford_Mondeo                                                         32
Volkswagen_Golf_1.9_TDI                                             32
Fiat_Punto                                                          32
Ford_Ka                                                             30
Volkswagen_Lupo_1.0                                                 29
Renault_Clio                                                        29
                                                                    ..
Toyota_4_Runner_V6_Special_79603_km_Original                         1
_Zu_Verkaufen__Opel_Corsa_1.0_12V_World_Cup                          1
Ford__Focus_C_max_1.6_16_v_TDCi_Automatik_AHK_Diesel_Unfallfrei      1
BMW_E_46_Touring                                                     1
Mazda_6_SKYACTIV_D_175_2_2_Sports_Line_5Jahre_Garantie               1
Opel__ZAFIRA_7_Sitzer___TÃœV_neu                                      1
twingo_bj.03_tuev_7/16_servo_klima_leder_e_fenster_1250_VB           1
BMW_530d_M_Paket_Shadowline                                          1
BMW_320i_Touring_Aut.__Leder_SHZ__PDC__Pano__Alu                     1
Volkswagen_Golf_1.6_TDI_DPF_Style_Navi._Sehr_gepflegt!               1
Volvo_S60_D3_Geartronic.mwst_ausweisbar                              1
CitroÃ«n_C3_Pluriel_HDi_70                                            1
Cross_Polo_schwarz_metallic_mit_TÃœV                                  1
Hyundai_i30cw_1.6_Comfort_Klima_Parkdistanzkontrolle_Langstrecke     1
Rover_25_TÃœV_05/16                                                   1
Audi_A4_Avant_2.0_TDI_DPF_*BI_XENON*NAVI_MMI*                        1
VW_PASSAT                                                            1
Nissan_qashqai+2                                                     1
Opel_Atra_G_Cabrio_1_6_Linea_Rossa_in_Chiantirot_So/Wi_Reifen        1
Volkswagen_Scirocco_2.0_TDI_DSG_GTS                                  1
Zuverlaessiges_klein_wagen                                           1
Vw_Polo_6n_5_Tuerer                                                  1
APE_50___deutsche_Papiere_!!!                                        1
Volkswagen_Corrado_3.0_VR6_Kompressor                                1
PORSCHE__CAYENNE                                                     1
Nissan_Primastar_*Tuev_Neu*_no_Trafic_Vivaro_T5_T4                   1
Volkswagen_Golf_Variant_1.9_TDI_Special_Klima_Sitzhzg_HUneu          1
Opel_Astra_2.2_16V_Coupe_Linea_Rossa                                 1
BMW_540i_4_4_LITER_286PS_Gepflegt_und_Top_Zustand                    1
Golf_2_mit_TÃœV                                                       1
Name: name, Length: 38754, dtype: int64

In [15]:
autos['price'].value_counts()

$0          1421
$500         781
$1,500       734
$2,500       643
$1,200       639
$1,000       639
$600         531
$800         498
$3,500       498
$2,000       460
$999         434
$750         433
$900         420
$650         419
$850         410
$700         395
$4,500       394
$300         384
$2,200       382
$950         379
$1,100       376
$1,300       371
$3,000       365
$550         356
$1,800       355
$5,500       340
$350         335
$1,250       335
$1,600       327
$1,999       322
            ...
$2,695         1
$6,039         1
$16,975        1
$34,150        1
$1,432         1
$79,500        1
$21,888        1
$3,318         1
$3,211         1
$18,470        1
$19,968        1
$55,996        1
$1,189         1
$28,300        1
$29            1
$37,300        1
$7,085         1
$2,920         1
$1,984         1
$25,390        1
$15,249        1
$12,690        1
$18,890        1
$4,111         1
$24,360        1
$20,799        1
$155,000       1
$7,985         1
$4,598         1
$7,435         1
Name: price, Length: 2357, dtype: int64

In [16]:
autos['no_of_pictures'].value_counts()

0    50000
Name: no_of_pictures, dtype: int64

### Observations
- `seller` and `offer_type` only have 2 unique values. The secong unique value has one occurence. `no_of_pictures` is all zeros.
- `name` column has 38754 unique values out of 50000. It appears that options are included in the names making it difficult to compare similar models
- `date_crawled`, `ad_created`, `last_seen` need to be datetime
- `postal_code`, `registration_year` needs to be string
- `price`, `odometer` need to be floats

In [17]:
# clean `price`column
autos['price'] = (autos['price']
                  .str.replace("$","")
                  .str.replace(',','')
                  .astype(int)
                 )

In [18]:
# clean `odometer` column
autos['odometer'] = (autos['odometer']
                    .str.replace('km','')
                    .str.replace(',','')
                    .astype(int)
                    )

In [19]:
# rename `odometer` column to `odometer_km`
autos.rename(columns={'odometer':'odometer_km'},inplace=True)

In [20]:
# confirm name change for `odometer`
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'powerPS', 'model',
       'odometer_km', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'no_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

In [21]:
# confirm type change for `price` and `odometer_km'
autos.dtypes

date_crawled          object
name                  object
seller                object
offer_type            object
price                  int64
abtest                object
vehicle_type          object
registration_year      int64
gearbox               object
powerPS                int64
model                 object
odometer_km            int64
registration_month     int64
fuel_type             object
brand                 object
unrepaired_damage     object
ad_created            object
no_of_pictures         int64
postal_code            int64
last_seen             object
dtype: object

## Exploring the Odometer and Price Columns

In [22]:
autos['price'].unique().shape

(2357,)

In [23]:
autos['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [24]:
autos['price'].value_counts().sort_index(ascending=False).head(20)

99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: price, dtype: int64

In [25]:
autos[autos['price'].between(1,351000)].describe()

,price,registration_year,powerPS,odometer_km,registration_month,no_of_pictures,postal_code
count,48565.000000,48565.000000,48565.000000,48565.000000,48565.000000,48565.0,48565.000000
mean,5888.935591,2004.755421,117.197158,125770.101925,5.782251,0.0,50975.745207
std,9059.854754,88.643887,200.649618,39788.636804,3.685595,0.0,25746.968398
min,1.000000,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.000000
25%,1200.000000,1999.000000,71.000000,125000.000000,3.000000,0.0,30657.000000
50%,3000.000000,2004.000000,107.000000,150000.000000,6.000000,0.0,49716.000000
75%,7490.000000,2008.000000,150.000000,150000.000000,9.000000,0.0,71665.000000
max,350000.000000,9999.000000,17700.000000,150000.000000,12.000000,0.0,99998.000000

- the `price` column as a very wide range. There are more than 1400 listed with a price of 0. The top 10 highest are more than 350000. We'll keep everything between 1 and 351000. Many auctions begin at 1.

In [26]:
# filter high and lows out of autos based on price
autos = autos[autos['price'].between(1,351000)]

In [27]:
# confirm filter
autos.describe()

,price,registration_year,powerPS,odometer_km,registration_month,no_of_pictures,postal_code
count,48565.000000,48565.000000,48565.000000,48565.000000,48565.000000,48565.0,48565.000000
mean,5888.935591,2004.755421,117.197158,125770.101925,5.782251,0.0,50975.745207
std,9059.854754,88.643887,200.649618,39788.636804,3.685595,0.0,25746.968398
min,1.000000,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.000000
25%,1200.000000,1999.000000,71.000000,125000.000000,3.000000,0.0,30657.000000
50%,3000.000000,2004.000000,107.000000,150000.000000,6.000000,0.0,49716.000000
75%,7490.000000,2008.000000,150.000000,150000.000000,9.000000,0.0,71665.000000
max,350000.000000,9999.000000,17700.000000,150000.000000,12.000000,0.0,99998.000000

In [28]:
autos['odometer_km'].value_counts()

150000    31414
125000     5057
100000     2115
90000      1734
80000      1415
70000      1217
60000      1155
50000      1012
5000        836
40000       815
30000       780
20000       762
10000       253
Name: odometer_km, dtype: int64

- mileage values appear to be rounded to the 0. Either everybody rounded or there were buckets for people to select. There are more high mileage cars than low mileage, which makes sense for an auction site.

## Exploring the date columns

- `date_crawled`: added by the crawler
- `last_seen`: added by the crawler
- `ad_created`: from the website
- `registration_month`: from the website
- `registration_year`: from the website

In [29]:
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False)

2016-04-03    0.038608
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-12    0.036920
2016-03-14    0.036549
2016-04-04    0.036487
2016-03-07    0.036014
2016-04-02    0.035478
2016-03-28    0.034860
2016-03-19    0.034778
2016-03-15    0.034284
2016-03-29    0.034099
2016-04-01    0.033687
2016-03-30    0.033687
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-22    0.032987
2016-03-11    0.032575
2016-03-23    0.032225
2016-03-26    0.032204
2016-03-10    0.032184
2016-03-31    0.031834
2016-03-17    0.031628
2016-03-25    0.031607
2016-03-27    0.031092
2016-03-16    0.029610
2016-03-24    0.029342
2016-03-05    0.025327
2016-03-13    0.015670
2016-03-06    0.014043
2016-04-05    0.013096
2016-03-18    0.012911
2016-04-06    0.003171
2016-04-07    0.001400
Name: date_crawled, dtype: float64

In [30]:
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index()

2016-03-05    0.025327
2016-03-06    0.014043
2016-03-07    0.036014
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-10    0.032184
2016-03-11    0.032575
2016-03-12    0.036920
2016-03-13    0.015670
2016-03-14    0.036549
2016-03-15    0.034284
2016-03-16    0.029610
2016-03-17    0.031628
2016-03-18    0.012911
2016-03-19    0.034778
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-22    0.032987
2016-03-23    0.032225
2016-03-24    0.029342
2016-03-25    0.031607
2016-03-26    0.032204
2016-03-27    0.031092
2016-03-28    0.034860
2016-03-29    0.034099
2016-03-30    0.033687
2016-03-31    0.031834
2016-04-01    0.033687
2016-04-02    0.035478
2016-04-03    0.038608
2016-04-04    0.036487
2016-04-05    0.013096
2016-04-06    0.003171
2016-04-07    0.001400
Name: date_crawled, dtype: float64

In [31]:
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).describe()

count    34.000000
mean      0.029412
std       0.009762
min       0.001400
25%       0.029980
50%       0.032781
75%       0.034840
max       0.038608
Name: date_crawled, dtype: float64

- the filtered autos dataset shows autos listed from 34 dates between 2016-03-05 and 2016-04-07. 
- The date with the highest percentage of crawls was 2016-04-03 (3.86%)
- we could say that the distribution of visits was relatively even

In [32]:
(autos['last_seen']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .sort_index()
)

2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-08    0.007413
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-12    0.023783
2016-03-13    0.008895
2016-03-14    0.012602
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-17    0.028086
2016-03-18    0.007351
2016-03-19    0.015834
2016-03-20    0.020653
2016-03-21    0.020632
2016-03-22    0.021373
2016-03-23    0.018532
2016-03-24    0.019767
2016-03-25    0.019211
2016-03-26    0.016802
2016-03-27    0.015649
2016-03-28    0.020859
2016-03-29    0.022341
2016-03-30    0.024771
2016-03-31    0.023783
2016-04-01    0.022794
2016-04-02    0.024915
2016-04-03    0.025203
2016-04-04    0.024483
2016-04-05    0.124761
2016-04-06    0.221806
2016-04-07    0.131947
Name: last_seen, dtype: float64

In [33]:
(autos['last_seen']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .sort_values()
)

2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-18    0.007351
2016-03-08    0.007413
2016-03-13    0.008895
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-14    0.012602
2016-03-27    0.015649
2016-03-19    0.015834
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-26    0.016802
2016-03-23    0.018532
2016-03-25    0.019211
2016-03-24    0.019767
2016-03-21    0.020632
2016-03-20    0.020653
2016-03-28    0.020859
2016-03-22    0.021373
2016-03-29    0.022341
2016-04-01    0.022794
2016-03-31    0.023783
2016-03-12    0.023783
2016-04-04    0.024483
2016-03-30    0.024771
2016-04-02    0.024915
2016-04-03    0.025203
2016-03-17    0.028086
2016-04-05    0.124761
2016-04-07    0.131947
2016-04-06    0.221806
Name: last_seen, dtype: float64

In [34]:
(autos['last_seen']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .describe()
)

count    34.000000
mean      0.029412
std       0.043718
min       0.001071
25%       0.012432
50%       0.019489
75%       0.023783
max       0.221806
Name: last_seen, dtype: float64

- again we see 34 values, with dates ranging from 2016-03-05 to 2016-04-06
- the last three dates show a larger percentage of views compared to previous days.
- it's unlikely that these represent car sales and are an artifact of the crawler

In [35]:
(autos['ad_created']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .sort_index()
)

2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
2015-12-30    0.000021
2016-01-03    0.000021
2016-01-07    0.000021
2016-01-10    0.000041
2016-01-13    0.000021
2016-01-14    0.000021
2016-01-16    0.000021
2016-01-22    0.000021
2016-01-27    0.000062
2016-01-29    0.000021
2016-02-01    0.000021
2016-02-02    0.000041
2016-02-05    0.000041
2016-02-07    0.000021
2016-02-08    0.000021
2016-02-09    0.000021
2016-02-11    0.000021
2016-02-12    0.000041
2016-02-14    0.000041
2016-02-16    0.000021
2016-02-17    0.000021
2016-02-18    0.000041
2016-02-19    0.000062
2016-02-20    0.000041
2016-02-21    0.000062
                ...
2016-03-09    0.033151
2016-03-10    0.031895
2016-03-11    0.032904
2016-03-12    0.036755
2016-03-13    0.017008
2016-03-14    0.035190
2016-03-15    0.034016
2016-03-16    0.030125
2016-03-17    0.031278
2016-03-18    0.013590
2016-03-19    0.033687
2016-03-20    0.037949
2016-03-21    0.037579
2016-03-22    0.032801
2016-03-23    0.032060
2016-03-24    0.029280
2016-03-25    0.031751
2016-03-26    0.032266
2016-03-27    0.030989
2016-03-28    0.034984
2016-03-29    0.034037
2016-03-30    0.033501
2016-03-31    0.031875
2016-04-01    0.033687
2016-04-02    0.035149
2016-04-03    0.038855
2016-04-04    0.036858
2016-04-05    0.011819
2016-04-06    0.003253
2016-04-07    0.001256
Name: ad_created, Length: 76, dtype: float64

In [36]:
(autos['ad_created']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .sort_values(ascending=False)
)

2016-04-03    0.038855
2016-03-20    0.037949
2016-03-21    0.037579
2016-04-04    0.036858
2016-03-12    0.036755
2016-03-14    0.035190
2016-04-02    0.035149
2016-03-28    0.034984
2016-03-07    0.034737
2016-03-29    0.034037
2016-03-15    0.034016
2016-03-19    0.033687
2016-04-01    0.033687
2016-03-30    0.033501
2016-03-08    0.033316
2016-03-09    0.033151
2016-03-11    0.032904
2016-03-22    0.032801
2016-03-26    0.032266
2016-03-23    0.032060
2016-03-10    0.031895
2016-03-31    0.031875
2016-03-25    0.031751
2016-03-17    0.031278
2016-03-27    0.030989
2016-03-16    0.030125
2016-03-24    0.029280
2016-03-05    0.022897
2016-03-13    0.017008
2016-03-06    0.015320
                ...
2016-02-26    0.000041
2016-02-14    0.000041
2016-02-02    0.000041
2016-02-05    0.000041
2016-02-18    0.000041
2016-02-20    0.000041
2016-02-24    0.000041
2016-02-12    0.000041
2016-01-10    0.000041
2016-02-17    0.000021
2016-01-13    0.000021
2016-02-09    0.000021
2015-06-11    0.000021
2015-12-30    0.000021
2016-02-07    0.000021
2016-01-29    0.000021
2016-01-03    0.000021
2015-11-10    0.000021
2016-02-22    0.000021
2016-02-11    0.000021
2015-08-10    0.000021
2016-02-16    0.000021
2016-01-16    0.000021
2015-12-05    0.000021
2016-02-08    0.000021
2015-09-09    0.000021
2016-01-14    0.000021
2016-02-01    0.000021
2016-01-07    0.000021
2016-01-22    0.000021
Name: ad_created, Length: 76, dtype: float64

In [37]:
(autos['ad_created']
 .str[:10]
 .value_counts(normalize=True, dropna=False)
 .describe()
)

count    76.000000
mean      0.013158
std       0.015956
min       0.000021
25%       0.000021
50%       0.000144
75%       0.032112
max       0.038855
Name: ad_created, dtype: float64

- there are 76 values in the `ad_created` column
- there is more variation in this column ranging between 0.0021% and 3.8855%
- there is a big jump between the 50th percentile and the 75th percentile
- these dates span a 9 month time period (2015-06-11 to 2016-04-07)

In [38]:
autos['registration_year'].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

In [39]:
autos['registration_year'].sort_values()

22316    1000
49283    1001
24511    1111
32585    1800
10556    1800
22659    1910
45157    1910
30781    1910
28693    1910
3679     1910
21416    1927
22101    1929
11246    1931
2221     1934
2573     1934
39725    1937
21421    1937
23804    1937
26607    1937
26103    1938
24855    1939
13963    1941
25792    1941
11585    1943
11047    1948
32091    1950
1171     1950
14020    1950
44406    1951
35921    1951
         ...
10222    2018
17813    2018
32202    2018
13244    2018
10167    2018
41371    2018
41372    2018
49354    2018
41378    2018
20730    2018
44772    2018
17928    2018
32040    2018
5763     2019
49185    2019
27578    2800
4549     4100
453      4500
42079    4800
4164     5000
22799    5000
49153    5000
24519    5000
27618    5911
8360     6200
25003    8888
49910    9000
8012     9999
38076    9999
33950    9999
Name: registration_year, Length: 48565, dtype: int64

- there are some year values that fall outside dates when cars even existed (1000), and before a date has even happened (like 9999)

## Dealing with Incorrect Registration Year Data

In [40]:
autos[autos['registration_year'].between(1900,2016)]['registration_year'].describe()

count    46681.000000
mean      2002.910756
std          7.185103
min       1910.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       2016.000000
Name: registration_year, dtype: float64

- if we filter the dates between 1900 and 2016, we end up with 46681 results
- the mean registration year of the car is 2002-2003
- most autos were registered in the last 20 years (relative to 2016)

In [41]:
autos = autos[autos['registration_year'].between(1900,2016)]

In [42]:
autos['registration_year'].value_counts(normalize=True)

2000    0.067608
2005    0.062895
1999    0.062060
2004    0.057904
2003    0.057818
2006    0.057197
2001    0.056468
2002    0.053255
1998    0.050620
2007    0.048778
2008    0.047450
2009    0.044665
1997    0.041794
2011    0.034768
2010    0.034040
1996    0.029412
2012    0.028063
1995    0.026285
2016    0.026135
2013    0.017202
2014    0.014203
1994    0.013474
1993    0.009104
2015    0.008397
1992    0.007926
1990    0.007433
1991    0.007262
1989    0.003727
1988    0.002892
1985    0.002035
          ...
1966    0.000471
1976    0.000450
1969    0.000407
1975    0.000386
1965    0.000364
1964    0.000257
1963    0.000171
1959    0.000129
1961    0.000129
1910    0.000107
1956    0.000086
1958    0.000086
1937    0.000086
1962    0.000086
1950    0.000064
1954    0.000043
1941    0.000043
1951    0.000043
1934    0.000043
1957    0.000043
1955    0.000043
1953    0.000021
1943    0.000021
1929    0.000021
1939    0.000021
1938    0.000021
1948    0.000021
1927    0.000021
1931    0.000021
1952    0.000021
Name: registration_year, Length: 78, dtype: float64

## Exploring Price by Brand

In [43]:
autos['brand'].value_counts(normalize=True).sort_values(ascending=False)

volkswagen        0.211264
bmw               0.110045
opel              0.107581
mercedes_benz     0.096463
audi              0.086566
ford              0.069900
renault           0.047150
peugeot           0.029841
fiat              0.025642
seat              0.018273
skoda             0.016409
nissan            0.015274
mazda             0.015188
smart             0.014160
citroen           0.014010
toyota            0.012703
hyundai           0.010025
sonstige_autos    0.009811
volvo             0.009147
mini              0.008762
mitsubishi        0.008226
honda             0.007840
kia               0.007069
alfa_romeo        0.006641
porsche           0.006127
suzuki            0.005934
chevrolet         0.005698
chrysler          0.003513
dacia             0.002635
daihatsu          0.002506
jeep              0.002271
subaru            0.002142
land_rover        0.002099
saab              0.001649
jaguar            0.001564
daewoo            0.001500
trabant           0.001392
rover             0.001328
lancia            0.001071
lada              0.000578
Name: brand, dtype: float64

- looks like it'd be good to take a peek at the brands that have 5% or more percent of the listings

In [44]:
brand_counts = autos["brand"].value_counts(normalize=True)
common_brands = brand_counts[brand_counts > .05].index
print(common_brands)

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object')

In [45]:
brand_mean_prices = {}

for brand in common_brands:
    brand_only = autos[autos['brand'] == brand]
    mean_price = brand_only['price'].mean()
    brand_mean_prices[brand] = int(mean_price)
    
brand_mean_prices

{'audi': 9336,
 'bmw': 8332,
 'ford': 3749,
 'mercedes_benz': 8628,
 'opel': 2975,
 'volkswagen': 5402}

- Audi, Mercedes-Benz, and BMW are in a class of their own (more than 1.5x the price of Volkswagen)
- Ford and Opel are at the bottom of the top 5%
- Volkswagen is right in the middle

## Exploring mileage

In [47]:
brand_mean_mileage = {}

for brand in common_brands:
    brand_only = autos[autos['brand']== brand]
    mean_mileage = brand_only['odometer_km'].mean()
    brand_mean_mileage[brand] = int(mean_mileage)
    
mean_mileage = pd.Series(brand_mean_mileage).sort_values(ascending=False)
mean_prices = pd.Series(brand_mean_prices).sort_values(ascending=False)

In [48]:
brand_info = pd.DataFrame(mean_mileage, columns=['mean_mileage'])

In [49]:
brand_info['mean_price'] = mean_prices

In [50]:
brand_info

               mean_mileage  mean_price
bmw                  132572        8332
mercedes_benz        130788        8628
opel                 129310        2975
audi                 129157        9336
volkswagen           128707        5402
ford                 124266        3749

- the mean mileages do not vary as much as the mean prices between brands

## Next Steps
In this guided project, we practiced applying a variety of pandas methods to explore and understand a data set on car listings. Here are some next steps for you to consider:

Data cleaning next steps:
- Identify categorical data that uses german words, translate them and map the values to their english counterparts
- Convert the dates to be uniform numeric data, so "2016-03-21" becomes the integer 20160321.
- See if there are particular keywords in the name column that you can extract as new columns

Analysis next steps:
- Find the most common brand/model combinations
- Split the odometer_km into groups, and use aggregation to see if average prices follows any patterns based on the milage.
- How much cheaper are cars with damage than their non-damaged counterparts?